#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."

REVOKE=false
EXPECT_DOMAIN=false
DOMAINS=""
for i in $@
    do
        if [ "$i" == "--revoke" ]; then 
            REVOKE=true
        elif $EXPECT_DOMAIN; then
            if [ "$DOMAINS" == "" ];then
                DOMAINS="$i"
            else
                DOMAINS="$i,$DOMAINS"
            fi
            EXPECT_DOMAIN=false
        elif [ "$i" == "--domain" ]; then
            EXPECT_DOMAIN=true 
        fi
    done

# echo "-challengeType=$1 -dir=$3 -record=$5 -domain=$DOMAINS -revoke=$REVOKE"
./acmeProject -challengeType=$1 -dir=$3 -record=$5 -domain=$DOMAINS -revoke=$REVOKE